export const PHYSICS_TIME_STEP_SECONDS = 1 / 240;
export const MAX_ROBOT_JOINT_SPEED_DEG_PER_SECOND = 1200;
export const MAX_ROBOT_JOINT_STEP_DEG =
  MAX_ROBOT_JOINT_SPEED_DEG_PER_SECOND * PHYSICS_TIME_STEP_SECONDS;
